### ISSUE TITLE
[Bug] The Login API returns weird prefix message when failed

### ISSUE THREAD

**Issue by minhnimble** [kyuuuyki/NimbleSurvey#11]
## Issue

When the API fails, the error prompt provides a weird prefix message `URLSessionTask failed with error:`. This is actually not needed as it is more of a technical term that doesn't really provide any additionally useful information on the API issue from the actual user's point of view.

| Turn off the internet access for an active connection | Turn off the internet connection |
|------------------------------------------------------|---------------------------------|
|<img src="https://user-images.githubusercontent.com/70877098/182076637-21ade3f7-2ccb-49fa-99a2-e7e58a8b621e.PNG" width="300">|<img src="https://user-images.githubusercontent.com/70877098/182076633-91e43478-bc1c-4d42-962d-3d275a6eff79.PNG" width="300">|

## Expect
The weird technical prefix message should be omitted when calling the Login API and fails.

## Step to reproduce

1. Starting the application freshly.
2. Type in a valid email/password combination on the Login screen.
3. Turn off the Wifi internet connection/Setup an invalid proxy server manually on the current Wifi connection.
4. Select the `Log in` button.
5. Observe the result.

**Comment by kyuuuyki** [comment]
Fixed in https://github.com/kyuuuyki/NimbleSurvey/pull/29
