### ISSUE TITLE
[Bug] Starting the app without the internet connection will stuck at the shimmer loading indicator forever

### ISSUE THREAD

**Issue by minhnimble** [kyuuuyki/NimbleSurvey#12]
## Issue

When starting the application without the internet connection, if there is a previously logged session, the user will see the shimmer loading indicator screen with some error messages about not having the internet connection. Unfortunately, turning the internet connection back online does nothing and the application is stuck there forever.

## Expect

When starting the application without the internet connection, if there is a previously logged session, there should be an option for the user to retry to reload the data instead of blocking the user forever at the shimmer loading indicator.

## Step to reproduce

https://user-images.githubusercontent.com/70877098/182095870-0c7a8cc6-b6de-4b70-abd7-c39be03dc4f1.MP4

**Comment by kyuuuyki** [comment]
SurveyListScene's errorView and retryButton provided here https://github.com/kyuuuyki/NimbleSurvey/pull/21.
