### ISSUE TITLE
[Bug] The survey item content on the Survey List screen is difficult to see and doesn't match with the design

### ISSUE THREAD

**Issue by minhnimble** [kyuuuyki/NimbleSurvey#13]
## Issues

There are a few UI issues with the survey contents in the Survey List screen. I would like to list them as follow:
- The display image for each survey item is very blurry.
- We would not be able to see the status bar clearly as the texts are in black for Light mode.

Example screenshot:

<img src="https://user-images.githubusercontent.com/70877098/182098947-01412d1d-554e-4080-b94a-060edc357a88.PNG" width="300">

## Expect

The survey content must be clear and properly displayed regardless of the image content or the Light or Dark mode like the design:

<img src="https://user-images.githubusercontent.com/70877098/159682538-5934d10f-fd97-4c01-b95a-28b0c6199ed8.png" width="300">

## Step to reproduce

1. Start the application freshly.
2. Login with a valid credential.
3. Swipe to view different surveys in the Survey List screen.
4. Observe the result.

**Comment by kyuuuyki** [comment]
Partially fixed in https://github.com/kyuuuyki/NimbleSurvey/pull/24.

**Comment by minhnimble** [comment]
@kyuuuyki just a friendly reminder, from the [Get Survey List API in Postman](https://documenter.getpostman.com/view/11835486/UVsPNPfU#064357a5-4625-4ef7-b042-0d1f7e2f2acb) we provide, there is a way for retrieving better image quality and you probably have missed that. 😅

**Comment by kyuuuyki** [comment]
Ohhh... how do I miss that... 😰 

Fixed in https://github.com/kyuuuyki/NimbleSurvey/pull/26.
