### ISSUE TITLE
[Question] Application environment handling concern

### ISSUE THREAD

**Issue by minhnimble** [kyuuuyki/NimbleSurvey#14]
## Issue
As per our API [documentation](https://github.com/nimblehq/nimble-survey-web/wiki/REST-API#ios), there are more environments that our API should be able to support, which are Staging and Production, and you only handled the Production environment so far as follows. I would like to know more about if you have any experience in handling different environments in a project and if yes, how would you do it in such cases?

https://github.com/kyuuuyki/NimbleSurvey/blob/b9279c64fba0d01aa01f4cffcbaa1e6542ca2e33/Modules/NimbleCoreAPI/NimbleCoreAPI/Classes/NimbleCoreAPI.swift#L11-L20

**Comment by kyuuuyki** [comment]
I've done some environment handling by using multiple schemes and configuration files.

Can you please provide me ClientID and ClientSecret for staging env? I've got only production's via my email.

I've downloaded Postman collection by wiki's link from this [file](https://docs.google.com/document/d/1CpbVBdyFmKKYO2BhAxam0_Cz9ByMKsnXNX-Jmeb3M80/edit) but it seems to be that Staging is missing, can I just use `https://nimble-survey-web-staging.herokuapp.com/api/v1` for Staging?

**Comment by minhnimble** [comment]
@kyuuuyki As of this point, our `Staging` environment is actually not available due to some internal issues, and thus `ClientID` and `ClientSecret` for the Staging environment can’t be provided. 

Regarding the raised issue, I mainly want to know more about your experiences in handling different environments in iOS as currently, it can be seen that your submission doesn’t show your experience in this field. It would be helpful if you can elaborate more and describe in detail how you use multiple schemes and configuration files to handle different environments. 🙏

**Comment by kyuuuyki** [comment]
### Configuration Files
I've created `.xcconfig` files named `Production` and `Staging`. 

### Schemes
Configuration files will be used by the corresponding schemes named `Nimble Production` and `Nimble Staging`.

### NimbleCoreAPI
Each scheme will produce a different value for `Environment` variable in `Info.plist` file. This variable is used to determine `NimbleCoreAPI`'s environment.

Handled in https://github.com/kyuuuyki/NimbleSurvey/pull/25.
