### ISSUE TITLE
[Bug] Redudant animation shows when swipping for more contents in the Survey List screen

### ISSUE THREAD

**Issue by minhnimble** [kyuuuyki/NimbleSurvey#16]
## Issue

When scrolling to the left on the first page or to the right on the last page, there is a weird fading animation that should not happen as there is no new item to animate and show.

## Expect

The fade animation when transitioning between pages should not happen when scrolling for more at first/last item position.

## Steps to reproduce

https://user-images.githubusercontent.com/70877098/182105485-879ae994-1f66-4305-97ce-94a29c6e0b2f.mov

**Comment by kyuuuyki** [comment]
Fixed in https://github.com/kyuuuyki/NimbleSurvey/pull/22
