### ISSUE TITLE
[Bug] Page indicator fails to navigate to a new page when the users tapping dirrectly on it

### ISSUE THREAD

**Issue by minhnimble** [kyuuuyki/NimbleSurvey#17]
## Issue

When tapping on the page indicator to open a specific page, the page indicator doesn't do anything and user can only swipe to navigate between the survey item.

## Expect

Tapping on the page indicator should allow user to navigate to the selected page. 

## Steps to reproduce

https://user-images.githubusercontent.com/70877098/182105712-7bea1ec3-7b60-4bc5-8bec-b889909c389b.mov

**Comment by kyuuuyki** [comment]
Fixed in https://github.com/kyuuuyki/NimbleSurvey/pull/28
