### ISSUE TITLE
Start of the code review process 🥸

### ISSUE THREAD

**Issue by minhnimble** [kyuuuyki/NimbleSurvey#8]
Hello Chayanon 👋 , thank you for your effort on the code submission. I am Mike, acting as an Engineer Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by minhnimble** [comment]
Hello Chayanon again 👋, just FYI I complete the 1st round of review just now. Please go ahead and provide your feedback on all the proposed issues.

Have a great week start! ☀️

**Comment by minhnimble** [comment]
Hello, Chayanon 👋

I also complete the 2nd round of review just now. Again, you can start providing your feedback on all the new comments and remaining issues at this point.

Have a great morning! ☀️

**Comment by minhnimble** [comment]
Good afternoon, Chayanon  ☀️

As of this point, this code challenge review session reaches a conclusion and thus no more submission or comment will be needed from your end. For the next step, you will be hearing from the Talent Acquisition team about the decision as soon as it is available. 🙏

In the end, it was a pleasure reviewing your code and getting to know you. Thanks for your time and I wish you all the best! 🍀

**Comment by kyuuuyki** [comment]
Thanks, @minhnimble! 🙏

This review session taught me so many aspects of both the code review process and technical points of view and I've learned much more about new exciting things.

Thanks again. 😃
