### ISSUE TITLE
[Question] UI Testing and 3rd-party libraries knowledge concerns

### ISSUE THREAD

**Issue by minhnimble** [kyuuuyki/NimbleSurvey#9]
## Issues

I noticed that you have written the unit tests for all the components of the VIPER architecture in the application with a great code coverage percentage, nice work there 👍. At the same time, there are no UI tests found in the application. I am wondering if you ever had the opportunity to write UI tests before? If yes, it would be great if you can demonstrate your skills with a simple UI test to verify some basic UI flows in the application. An example could be the flow to open the Home screen from the Login screen.

Furthermore, I would like to know if you have any experience in any other 3rd-party library for writing unit tests apart from the native XCTest? If yes, can you tell me a little bit more about how you would write tests using those libraries?

**Comment by kyuuuyki** [comment]
I have to admit that I never implemented UI tests on my current workplace's released projects before. But I've done some tests on my own experiment projects. Here's an example for this project https://github.com/kyuuuyki/NimbleSurvey/pull/23.

For the 3rd-party library for unit tests, I have never used them before but I'm interested to know more about them. Can you please suggest some? Thanks. 😃

**Comment by minhnimble** [comment]
> I have to admit that I never implemented UI tests on my current workplace's released projects before. But I've done some tests on my own experiment projects. Here's an example for this project https://github.com/kyuuuyki/NimbleSurvey/pull/23.

→ I am having tests failed issue when trying to run the your new UI tests on the iPhone SE - 3rd generation - iOS 15.5 Simulator. Consider checking it when you are available: 
![Screen Shot 2022-08-02 at 10 43 07](https://user-images.githubusercontent.com/70877098/182287275-3c5cd800-0990-4383-a7e1-920ecad7596d.png)

> For the 3rd-party library for unit tests, I have never used them before but I'm interested to know more about them. Can you please suggest some? Thanks. 😃

→ If you have the chance to look through our [Compass page about writing tests on iOS](https://nimblehq.co/compass/development/ios/testing/#tools---libraries), there are actually a list of options that you can refer from. Don't hesitate and go check out when you have the time 🚀

**Comment by kyuuuyki** [comment]
Fixed in https://github.com/kyuuuyki/NimbleSurvey/pull/27.


> → If you have the chance to look through our [Compass page about writing tests on iOS](https://nimblehq.co/compass/development/ios/testing/#tools---libraries), there are actually a list of options that you can refer from. Don't hesitate and go check out when you have the time 🚀


Many thanks for your recommendation. 
Never knew that Nimble's compass contains such many interesting things. 😄 
By the way, this `Quick/Nimble` look so familiar. Like it appears while creating a new pods. Definitely checking out after this!
